name: eShop Workshop CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"
  
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build Repo
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      DOTNET_MULTILEVEL_LOOKUP: false
      DOTNET_INSTALL_DIR: ${{ matrix.os == 'ubuntu-latest' && '' || 'dotnet' }}
    steps:
    - uses: actions/checkout@v4

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ${{ matrix.os == 'ubuntu-latest' && './global.json' || '.\global.json' }}

    - name: Build
      run: ${{ matrix.os == 'ubuntu-latest' && './build.sh' || '.\build.cmd' }}

    - name: Install .NET HTTPS Development Certificate
      if: matrix.os == 'ubuntu-latest'
      run: |
        dotnet tool update -g linux-dev-certs
        dotnet linux-dev-certs install

    - name: Test
      id: test
      # Can't run Docker on Windows agents yet
      if: matrix.os == 'ubuntu-latest'
      # Note that the space after the last double dash (--) is intentional
      run: >
        dotnet test ./eShop.sln
        --logger console --logger trx --logger html --logger GitHubActions
        --results-directory ./TestResults --blame
        -- 
        RunConfiguration.CollectSourceInformation=true
    
    - name: Publish Test Results
      if: (success() || steps.test.conclusion == 'failure') && matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: TestResults_${{ matrix.os }}
        path: ./TestResults